engines:
    duplication:
        enabled: true
        config:
            languages:
                - typescript
                - javascript
                - css
    eslint:
        enabled: true
    tslint:
        enabled: true
    csslint:
        enabled: true
    fixme:
        enabled: true
    ratings:
        paths:
            - "**.ts"
            - "**.js"
            - "**.css"

    exclude_paths:
        - "node_modules/**/*"
        - "tests/**/*"
